apiVersion: v1
kind: Service
metadata:
  labels:
    app: syslog
  name: syslog
  namespace: default
spec:
  ports:
  - port: 514
    protocol: UDP
    name: syslog
  - port: 9080
    protocol: TCP
    name: promtail
  selector:
    app: syslog
  type: NodePort
