apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog_appliance_alpine-deployment
  labels:
    app: syslog_appliance_alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog_appliance_alpine
  template:
    metadata:
      labels:
        app: syslog_appliance_alpine
    spec:
      containers:
      - name: syslog_appliance_alpine
        image: rsyslog/syslog_appliance_alpine
        ports:
        - containerPort: 514
          protocol: UDP