apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-deployment
  labels:
    app: syslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog
  template:
    metadata:
      labels:
        app: syslog
    spec:
      containers:
      - name: syslog
        image: rsyslog/syslog_appliance_alpine
        ports:
        - containerPort: 514
          protocol: UDP
        volumeMounts:
        - mountPath: /logs/hosts
          name: logfile-volume
      - name: promtail
        image: grafana/promtail:2.3.0
        ports:
        - containerPort: 9080
          protocol: TCP        
        volumeMounts:
        - mountPath: /logs/hosts
          name: logfile-volume
        - name: promtail-config
          mountPath: /etc/promtail/config.yml
          subPath: config.yml              
      securityContext:
        fsGroup: 1000
      volumes:
      - name: logfile-volume
        emptyDir: {}
      - name: promtail-config
        configMap:
          name: syslog-configmap
